version: "2.1"
services:
  code-server:
    build: .
    container_name: code-server
    environment:
      - PUID=0 # for root access
      - PGID=0 # for root access
      - PASSWORD=value
      - GIT_REPO=value
      - RCLONE_DATA=value
      - etc=etc
      - etc=etc
    ports:
      - 8080:8080
    restart: unless-stopped
