version: "2.1"
services:
  code-server:
    build: .
    container_name: code-server
    environment:
      - PASSWORD=value
      - PUID=0
      - PGID=0
    ports:
      - 8080:8080
    restart: unless-stopped
